name: Julie's Blog
author: JaeEun Yoo
baseurl:
description:
github: http://www.github.com/avsbdn0406

email: avsbdn1226@bme.gachon.ac.kr


##Make sure to edit the above fields, especially for disqus.


markdown: kramdown


defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "PET"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "Linux"
    values:
      layout: "post"
