name: Julie's Blog
author: JaeEun Yoo
baseurl:
description:
github: http://www.github.com/avsbdn0406
url : https://avsbdn0406.github.io/

email: avsbdn1226@bme.gachon.ac.kr


##Make sure to edit the above fields, especially for disqus.


markdown: kramdown

paginate : 10
# 고정주소
permalink : /:title

navigation:
  -title : Programming
  url : /post.html
  -title : PET
  url : /PET.html
  -title : Linux
  url : /Linux.html

disqus : true
disqus_shortname : julie

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "/linux"
      type: "posts"
    values:
      layout: "post"
